Fix/ub 1431 fix glog errors in provisioner (#212)
currently there are errors filling the provisioner logs that look like this:
ERROR: logging before flag.Parse: I0716 13:33:58.655590 1 controller.go:1063] volume "ibm-ubiquity-db" deleted from database ERROR: logging before flag.Parse: I0716 13:34:00.224200 1 controller.go:826] volume "ibm-ubiquity-db" for claim "ubiquity/ibm-
they seem to be caused by some change in glog (used by kuberentes)
this small fix removes them from the log.

(fix was taking from : https://github.com/cloudnativelabs/kube-router/commit/78a0aeb39793c86a7fcb9688bf63a72a6cbb4f90   )